version: 2
jobs:
  build:
     docker:
       - image: microsoft/aspnetcore-build
     environment:
       DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
       DOTNET_CLI_TELEMETRY_OPTOUT: 1
     steps:
       - checkout
       - run: echo "hello world"
       - run: dotnet restore
       - run: dotnet build
       - deploy:
           name: Deploy Master to Dokku
           command: |
             if [ "${CIRCLE_BRANCH}" == "master" ]; then
               ssh-keyscan -H 138.197.138.253 >> ~/.ssh/known_hosts
               git remote add production dokku@138.197.138.253:coretest
               git push production master
             fi
